name: PendingWhitelist
main: dev.darkspirit69.pendingwhitelist.PendingWhitelistPlugin
version: '${version}'
api-version: "1.20"
authors:
  - Dark_Spirit69
website: https://github.com/DarkSpirit006/PendingWhitelist
description: Tracks players rejected by the whitelist and provides GUI and command administration.

dependencies:
  server:
    SkinsRestorer:
      load: BEFORE
      required: false
      join-classpath: true
